{% set name = "lbsoftconfdb2clients" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/LbSoftConfDb2Clients-{{ version }}.tar.gz
  sha256: 686da30c9b10d0af1f953925a6c9028e748f8f959b5d70eb80f41a1edf5bbb07

build:
  number: 1
  noarch: python
  entry_points:
    - lb-sdb-query=LbSoftConfDb2Clients.LbSdbQuery:main
    - lb-sdb-add-platform=LbSoftConfDb2Clients.LbSdbAddPlatform:main
    - lb-sdb-release=LbSoftConfDb2Clients.LbSdbRelease:main
    - lb-sdb-setprojectprop=LbSoftConfDb2Clients.LbSdbSetProjectProperties:main
    - lb-sdb-setpvprop=LbSoftConfDb2Clients.LbSdbSetPVProperties:main
    - lb-sdb-buildtool=LbSoftConfDb2Clients.LbSdbBuildTool:main
    - lb-sdb-deletepv=LbSoftConfDb2Clients.LbSdbDeleteVersion:main
    - lb-sdb-dumpprojects=LbSoftConfDb2Clients.LbSdbDumpProjects:main
    - lb-sdb-generateVersionJSON=LbSoftConfDb2Clients.LbSdbGenerateVersionJSON:main
    - lb-sdb-import=LbSoftConfDb2Clients.LbSdbImport:main
    - lb-sdb-add-project=LbSoftConfDb2Clients.LbSdbAddProject:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nose >=1.0
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - lbcommon
    - lbenv
    - python >={{ python_min }}
    - six

test:
  imports:
    - LbSoftConfDb2Clients
  commands:
    - pip check
    - lb-sdb-query --help
    - lb-sdb-add-platform --help
    - lb-sdb-release --help
    - lb-sdb-setprojectprop --help
    - lb-sdb-setpvprop --help
    - lb-sdb-buildtool --help
    - lb-sdb-deletepv --help
    - lb-sdb-dumpprojects --help
    - lb-sdb-generateVersionJSON --help
    - lb-sdb-import --help
    - lb-sdb-add-project --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.cern.ch/lhcb-core/LbSoftConfDb2Clients
  summary: LHCb Software configuration database 2 clients
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
